### ISSUE TITLE
script updates the SG tag on some nodes and that affects internal communication

### ISSUE THREAD

**Issue by mukrishn** [redhat-performance/cloud-governance#485] opened 2022-10-03 14:18 UTC
**Describe the bug**
On adding a new `machinepool` to an existing AWS cluster ended up in `NotReady` nodes because of internal communication error, that's due to a wrong SG being tagged to those nodes by an external script. Based on the events, `cloud-governance-delete-user` had done something post creation and that has affected the node's SG. 
slack convo - https://coreos.slack.com/archives/CCX9DB894/p1664371739652329

This happens randomly on OSD as well as ROSA based clusters on adding extra `machinepool` post deployment.

**To Reproduce**
1. Create ROSA/OSD cluster on AWS
2. Add `machinepool`
3. Wait for it to fail, it happens randomly so you may have to repeat until it shows up

**Expected behavior**
Script should not update the SG tag on existing nodes

**Screenshots**
in Slack thread - https://coreos.slack.com/archives/CCX9DB894/p1664371739652329

**Additional context**
Manually updating the right SG to the instances makes it right.

**Comment by smalleni** [comment] 2022-10-03 18:35
Seems like it is caused by adding the "Name" tag here: https://github.com/redhat-performance/cloud-governance/blob/589d687646a5d58c63675c22847965d7872988e3/cloud_governance/aws/tag_cluster/tag_cluster_resouces.py#L64_L66

The issue is that the tag used by the security group in the machineset of OCP is different from what exists on the instance itself

Tags on the EC2 instance
```
"tagSet": {
            "items": [
                {
                    "key": "Budget",
                    "value": "PERF-SCALE"
                },
                {
                    "key": "User",
                    "value": "osdCcsAdmin"
                },
                {
                    "key": "Project",
                    "value": "PLATFORMS MANAGED SERVICES"
                },
                {
                    "key": "rosa_cluster_id",
                    "value": "1pqv25lg22i8v1b1lhe1cfvjpmcouidd"
                },
                {
                    "key": "rosa_region",
                    "value": "us-west-2"
                },
                {
                    "key": "LaunchTime",
                    "value": "2022/09/27 20:33:33"
                },
                {
                    "key": "Email",
                    "value": "osdCcsAdmin@redhat.com"
                },
                {
                    "key": "Environment",
                    "value": "TEST"
                },
                {
                    "key": "Owner",
                    "value": "RUSS ZALESKI"
                },
                {
                    "key": "rosa_cluster_name",
                    "value": "dry-keith"
                },
                {
                    "key": "Manager",
                    "value": "SAI SINDHUR MALLENI"
                },
                {
                    "key": "Budget",
                    "value": "PERF-SCALE"
                },
                {
                    "key": "Name",
                    "value": "perf-411-3574-lkcp6-sg-fe491"
                }
            ]
        }
    },
    "responseElements"
```

Tags used by the OCP machineset

```

securityGroups:
          - filters:
            - name: tag:Name
              values:
              - perf-411-3574-lkcp6-worker-sg
```

Is there a reason we need to manually mess with the `Name` tag?

**Comment by smalleni** [comment] 2022-10-03 18:35
cc: @athiruma @ebattat

**Comment by ashishkamra** [comment] 2022-10-03 19:22
Let's namespace the cloud-governance tags to avoid conflicts. So prefix each tag that cloud-governance automation wants to apply on the resources with "cg-". Or something like that.

**Comment by athiruma** [comment] 2022-10-04 12:54
Closing this PR, because this has been fixed.

**Closed by athiruma** 2022-10-04 12:54 UTC
